# Generated by Django 4.2.4 on 2023-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countdown", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word_length",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="word",
            name="word_text",
            field=models.CharField(max_length=100),
        ),
    ]
